name: "Connected android test"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:


jobs:
  connected-android-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [19, 26]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: execute permission for gradlew
        run: chmod +x gradlew

      - name: run connected android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
