name: "Connected android test"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:


jobs:
  connected-android-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedCheck
