name: "Emulator tests"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:


jobs:
  connected-android-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 31 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          script: ./gradlew createDebugCoverageReport

      - name: Upload code coverage report
        uses: codecov/codecov-action@v3
